# Запускать последовательно или конкурентно
concurency:
  use: false
  # Количество одновременно работающих горутин
  coeff: 5

# Описание серверов
servers:
  # Как коннектиться по ssh: "ADDR" | "NAME"
  use: "ADDR"
  # Список серверов
  list:
    - name: server1
      addr: 10.0.0.1
    - name: server2
      addr: 10.0.0.2

# Выполняемые удаленно команды
# Чтобы работало в цикле, то завершайте каждую запись `command` 
# командой выхода "... ; exit"
remote_command:
    # Команда
  - command: "ls -lah ; exit"
    # Использовать темплейт: `"SERVER_NAME"`, 
    # произойдет подмена в command на имя или адрес сервера
    is_template: false

# Выполняемая команда
command:
  # Предварительно необходимо установить:
  # - переменные окружения `export SSH_PASSWORD="{secret}" && export SSH_USER="{username}"`
  # - программу sshpass
  # Формат команды:
  # `... %s ... %s %s`
  # - Первый %s -- соберутся все параметры для ssh из command.params
  # - Второй %s -- подставится имя или адрес сервера из servers.list.name|addr:
  # - Третий %s -- команда из remote_command.command:
  main: sshpass -p "$SSH_PASSWORD" ssh -tt %s $SSH_USER@%s %s
  # Параметры команды ssh
  params:
    - -o "StrictHostKeyChecking=accept-new"
    - -o "PreferredAuthentications=password"
